#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TOOLS_DIR="${ROOT_DIR}/tools/fonts"
CACHE_DIR="${TOOLS_DIR}/.cache"
VENV_DIR="${ROOT_DIR}/.venv-fontgen"

ZIP_URL="https://littlelimit.net/arc/misaki/misaki_ttf_2021-05-05.zip"
ZIP_PATH="${CACHE_DIR}/misaki_ttf_2021-05-05.zip"
TTF_PATH="${ROOT_DIR}/tools/font_assets/misaki_gothic.ttf"
MAP_PATH="${TOOLS_DIR}/misaki_katakana_subset.map"

mkdir -p "${CACHE_DIR}"
mkdir -p "${ROOT_DIR}/tools/font_assets"
mkdir -p "${ROOT_DIR}/components/Display/src"

if [[ ! -f "${ZIP_PATH}" ]]; then
  curl -fsSL -o "${ZIP_PATH}" "${ZIP_URL}"
fi

if [[ ! -f "${TTF_PATH}" ]]; then
  unzip -p "${ZIP_PATH}" misaki_gothic.ttf > "${TTF_PATH}"
fi

if [[ ! -d "${VENV_DIR}" ]]; then
  python -m venv "${VENV_DIR}"
  "${VENV_DIR}/bin/python" -m pip install -U pip
  "${VENV_DIR}/bin/python" -m pip install freetype-py
fi

# Build bdfconv (host tool) on demand.
BDFCONV_DIR="${CACHE_DIR}/bdfconv"
BDFCONV_BIN="${BDFCONV_DIR}/bdfconv"
if [[ ! -x "${BDFCONV_BIN}" ]]; then
  mkdir -p "${BDFCONV_DIR}"
  base="https://raw.githubusercontent.com/olikraus/u8g2/master/tools/font/bdfconv"
  for f in \
    main.c bdf_font.c bdf_font.h bdf_glyph.c bdf_glyph.h bdf_kern.c bdf_map.c \
    bdf_parser.c bdf_rle.c bdf_tga.c fd.c fd.h bdf_8x8.c; do
    curl -fsSL -o "${BDFCONV_DIR}/${f}" "${base}/${f}"
  done
  cc -O2 -std=c99 -D_GNU_SOURCE -Wall -Wextra -o "${BDFCONV_BIN}" \
    "${BDFCONV_DIR}/main.c" \
    "${BDFCONV_DIR}/bdf_font.c" \
    "${BDFCONV_DIR}/bdf_glyph.c" \
    "${BDFCONV_DIR}/bdf_kern.c" \
    "${BDFCONV_DIR}/bdf_map.c" \
    "${BDFCONV_DIR}/bdf_parser.c" \
    "${BDFCONV_DIR}/bdf_rle.c" \
    "${BDFCONV_DIR}/bdf_tga.c" \
    "${BDFCONV_DIR}/fd.c" \
    "${BDFCONV_DIR}/bdf_8x8.c"
fi

emit_header() {
  echo '#include <stdint.h>'
  echo '#if defined ( ARDUINO ) && !defined ( PROGMEM )'
  echo ' #if __has_include(<pgmspace.h>)'
  echo '  #include <pgmspace.h>'
  echo ' #elif __has_include(<avr/pgmspace.h>) || defined(__AVR__)'
  echo '  #include <avr/pgmspace.h>'
  echo ' #else'
  echo '  #include <Arduino.h>'
  echo ' #endif'
  echo '#endif'
  echo '#ifndef PROGMEM'
  echo '#define PROGMEM'
  echo '#endif'
  echo ''
  echo '// Generated by tools/fonts/gen_misaki_u8g2.sh'
  echo ''
}

generate_font() {
  local px="$1"
  local bdf_path="${CACHE_DIR}/misaki_gothic_${px}.bdf"
  local tmp_out="${CACHE_DIR}/misaki_font_${px}.c"
  local font_name="$2"
  local out_cpp="$3"

  "${VENV_DIR}/bin/python" "${TOOLS_DIR}/ttf_to_bdf_subset.py" \
    --ttf "${TTF_PATH}" \
    --map "${MAP_PATH}" \
    --out "${bdf_path}" \
    --px "${px}" \
    --dpi 72 \
    --fontname "misaki_gothic"

  "${BDFCONV_BIN}" -v -b 0 -f 1 -M "${MAP_PATH}" "${bdf_path}" -o "${tmp_out}" -n "${font_name}"

  {
    emit_header
    sed "s/U8G2_FONT_SECTION(\\\"${font_name}\\\")/PROGMEM/g" "${tmp_out}" | \
      sed -E "s/^const uint8_t[[:space:]]+${font_name}/extern const uint8_t ${font_name}/"
  } > "${out_cpp}"

  rm -f "${tmp_out}"
  echo "Generated: ${out_cpp}"
}

generate_font 16 "fontMisakiGothic16_data" "${ROOT_DIR}/components/Display/src/font_misaki_gothic16.cpp"
generate_font 8 "fontMisakiGothic8_data" "${ROOT_DIR}/components/Display/src/font_misaki_gothic8.cpp"
